### ISSUE TITLE
Pressing the "Comments" button again, does not hide the comments again

### ISSUE THREAD

**Issue by ragerin** [pasqu4le/tingsmen#17]
After expanding the comments list, clicking the "Comments" button again, does not close/collapse the comments list.

**Comment by pasqu4le** [comment]
it does not indeed, why should it? 
I'm not really asking you, I just want to point out that nowhere in the law there is something about collapsing... so I didn't implement it and this is not a bug, but a feature you think it's missing. 

That said, I do not dislike the idea and you know what you have to do if you want it :)
